name: Testes Unitários

on:
  pull_request:
    branches: [ main ]  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências de testes
        run: |
          python -m pip install --upgrade pip

      - name: Rodar testes unitários
        run: |
          python -m unittest discover
